# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt
from ui.HeadWidget import HeadWidget
from ui.InputTextEdit import InputTextEdit
import ui.StyleSheet as qss


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1100)
        self.MainWindow = MainWindow

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)  # 启用鼠标跟踪
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.head_widget = HeadWidget(self.centralwidget, MainWindow)
        self.head_widget.setMouseTracking(True)  # 启用鼠标跟踪
        self.head_widget.setObjectName("head_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.head_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.head_btn_widget = QtWidgets.QWidget(self.head_widget)
        self.head_btn_widget.setMouseTracking(True)  # 启用鼠标跟踪
        self.head_btn_widget.setStyleSheet("")
        self.head_btn_widget.setObjectName("h_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.head_btn_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(385, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.minBtn = QtWidgets.QPushButton(self.head_btn_widget)
        self.minBtn.setObjectName("minBtn")
        self.horizontalLayout_2.addWidget(self.minBtn)
        self.restore_btn = QtWidgets.QPushButton(self.head_btn_widget)
        self.restore_btn.setObjectName("maxBtn")
        self.horizontalLayout_2.addWidget(self.restore_btn)
        self.exitBtn = QtWidgets.QPushButton(self.head_btn_widget)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout_2.addWidget(self.exitBtn)
        self.gridLayout.addWidget(self.head_btn_widget, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.head_widget)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMouseTracking(True)  # 启用鼠标跟踪
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setMouseTracking(True)  # 启用鼠标跟踪
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.msg_widget = QtWidgets.QWidget(self.widget_3)
        self.msg_widget.setMouseTracking(True)  # 启用鼠标跟踪
        self.msg_widget.setObjectName("msg_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.msg_widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.msg_widget.setStyleSheet("border:none")
        self.chat_area = QtWidgets.QScrollArea(self.msg_widget)
        self.chat_area.setMouseTracking(True)  # 启用鼠标跟踪
        self.chat_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chat_area.setWidgetResizable(True)
        self.chat_area.setObjectName("chat_area")

        self.chat_widget = QtWidgets.QWidget()
        self.chat_widget.setMouseTracking(True)  # 启用鼠标跟踪
        self.chat_widget.setGeometry(QtCore.QRect(0, 0, 647, 446))
        self.chat_widget.setObjectName("chat_widget")

        self.chat_widget_layout = QtWidgets.QGridLayout(self.chat_widget)
        self.chat_widget_layout.setContentsMargins(0, 0, 0, 0)
        self.chat_widget_layout.setSpacing(0)
        self.chat_widget_layout.setObjectName("chat_widget_layout")
        self.chat_area.setWidget(self.chat_widget)
        self.gridLayout_3.addWidget(self.chat_area, 0, 0, 1, 1)

        self.verticalLayout.addWidget(self.msg_widget)

        self.input_area = QtWidgets.QWidget(self.widget_3)
        self.input_area.setMouseTracking(True)  # 启用鼠标跟踪
        self.input_area.setObjectName("input_area")
        self.input_area.setFixedHeight(100)

        self.textEdit = InputTextEdit(self.input_area)
        self.textEdit.setObjectName("inputEdit")

        self.textEdit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)  # 禁用垂直滚动条
        self.textEdit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)  # 禁用水平滚动条
        self.textEdit.verticalScrollBar().setValue(self.textEdit.verticalScrollBar().maximum())

        self.verticalLayout.addWidget(self.input_area)

        self.verticalLayout.setStretch(0, 7)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.widget_3)
        self.horizontalLayout.setStretch(0, 3)
        self.verticalLayout_2.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.translateUi(MainWindow)
        self.minBtn.clicked.connect(MainWindow.showMinimized)  # type: ignore
        self.restore_btn.clicked.connect(MainWindow.showFullScreen)  # type: ignore
        self.exitBtn.clicked.connect(MainWindow.close)  # type: ignore

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def translateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.exitBtn.setStyleSheet(qss.exitBtn)
        self.minBtn.setStyleSheet(qss.minBtn)
        self.restore_btn.setStyleSheet(qss.restore_btn)
        self.chat_widget.setStyleSheet(qss.chat_widget)
        self.head_btn_widget.setStyleSheet(qss.head_btn_widget)
        self.chat_area.verticalScrollBar().setStyleSheet(qss.chat_area_verticalScrollBar)

