# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui.HeadWidget import HeadWidget
from ui.InputTextEdit import InputTextEdit
from PyQt5.QtCore import Qt
import ui.StyleSheet as qss


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 600)
        self.main_widget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_widget.sizePolicy().hasHeightForWidth())
        self.main_widget.setSizePolicy(sizePolicy)
        self.main_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.main_widget.setMouseTracking(True)

        self.main_widget.setObjectName("main_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.head_widget = HeadWidget(self.main_widget, MainWindow)
        self.head_widget.setMouseTracking(True)
        self.head_widget.setMinimumSize(QtCore.QSize(0, 50))
        self.head_widget.setObjectName("head_widget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.head_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.min_btn = QtWidgets.QPushButton(self.head_widget)
        self.min_btn.setObjectName("min_btn")
        self.horizontalLayout.addWidget(self.min_btn)
        self.resize_btn = QtWidgets.QPushButton(self.head_widget)
        self.resize_btn.setObjectName("resize_btn")
        self.horizontalLayout.addWidget(self.resize_btn)
        self.exit_btn = QtWidgets.QPushButton(self.head_widget)
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn)
        self.verticalLayout.addWidget(self.head_widget)
        self.view_widget = QtWidgets.QWidget(self.main_widget)
        self.view_widget.setMouseTracking(True)

        self.view_widget.setObjectName("view_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.view_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.msg_widget = QtWidgets.QWidget(self.view_widget)
        self.msg_widget.setMouseTracking(True)

        self.msg_widget.setObjectName("msg_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.msg_widget)
        self.gridLayout.setContentsMargins(15, 0, 15, 15)
        self.gridLayout.setObjectName("gridLayout")

        self.scroll_area = QtWidgets.QScrollArea(self.msg_widget)
        self.scroll_area.setMouseTracking(True)
        self.scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

        self.scroll_widget = QtWidgets.QWidget()
        self.scroll_widget.setMouseTracking(True)
        self.scroll_widget.setGeometry(QtCore.QRect(0, 0, 812, 485))
        self.scroll_widget.setObjectName("scroll_widget")

        self.scroll_area.setWidget(self.scroll_widget)
        self.gridLayout.addWidget(self.scroll_area, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.msg_widget)

        self.scroll_widget_layout = QtWidgets.QGridLayout(self.scroll_widget)
        self.scroll_widget_layout.setContentsMargins(0, 0, 0, 0)
        self.scroll_widget_layout.setSpacing(20)
        self.scroll_widget_layout.setObjectName("scroll_widget_widget_layout")

        self.input_widget = QtWidgets.QWidget(self.view_widget)
        self.input_widget.setFixedHeight(100)
        self.input_widget.setMouseTracking(True)

        self.input_widget.setObjectName("input_widget")
        self.verticalLayout_2.addWidget(self.input_widget)

        self.input_edit = InputTextEdit(self.input_widget)
        self.input_edit.setObjectName("input_edit")
        self.input_edit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)  # 禁用垂直滚动条
        self.input_edit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)  # 禁用水平滚动条

        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.view_widget)
        MainWindow.setCentralWidget(self.main_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.min_btn.clicked.connect(MainWindow.showMinimized)  # type: ignore
        self.exit_btn.clicked.connect(MainWindow.close)  # type: ignore

        self.main_widget.setContentsMargins(0,0,0,0)
        self.main_widget.setStyleSheet("QWidget#main_widget{background-color:rgb(50,50,50);}")
        self.min_btn.setStyleSheet(qss.min_btn)
        self.resize_btn.setStyleSheet(qss.resize_btn)
        self.exit_btn.setStyleSheet(qss.exit_btn)
        self.input_widget.setStyleSheet(qss.input_widget)
        self.view_widget.setStyleSheet("QWidget#view_widget{background-color:rgb(33,33,33);}")
        self.msg_widget.setStyleSheet("QWidget#msg_widget{background-color:rgb(33,33,33);}")
        self.scroll_area.setStyleSheet("QScrollArea{background-color:rgb(33,33,33);}")
        self.scroll_widget.setStyleSheet("QWidget#scroll_widget{background-color:rgb(33,33,33);}")
        self.scroll_area.verticalScrollBar().setStyleSheet(qss.verticalScrollBar)
